config/routes.rb
Polco3::Application.routes.draw do

  resources :roles

  get "home/polco_info"

  resources :rolls do
    resources :comments
  end

  resources :bills do
    resources :comments
  end

  resources :legislators do
    resources :comments
  end

  resources :subjects

  # sign up a user for a district
  match "/users/geocode" => "users#geocode"
  match "/users/save_geocode" => "users#save_geocode"
  match "/users/district" => "users#district"

  get "polco_groups/add_custom_group"
  post "polco_groups/follow_group"
  post "polco_groups/join_group"

  resources :polco_groups do
    resources :comments
  end

  resources :legislator_votes # necessary?
  resources :votes

  resources :identities

  # what bills are active?
  get "represent/house_bills"
  get "represent/senate_bills"
  # how are the legislators voting?
  get "represent/legislators_districts"
  get "represent/states"
  # how are you being represented?
  # H3. and S3 house results -- how represented are you in the house?
  match "/represent/:chamber" => "represent#results", as: :results
  # helper to add vote
  post "rolls/add_vote", as: :add_vote

  root to: "represent#house_bills"
  resources :users, :only => [:index, :show, :edit, :update ] do
    resources :comments
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/signin', to: 'sessions#new', as: :signin
  match '/signout', to: 'sessions#destroy', as: :signout
  match '/auth/failure', to: 'sessions#failure'
end

app/models/bill.rb
class Bill
  include Mongoid::Document

  field :title, type: String
  field :title_without_number, type: String
  field :govtrack_id, type: String
  field :bill_resolution_type, type: String
  field :bill_type, type: String
  field :congress, type: Integer
  field :current_status, type: String
  field :current_status_label, type: String
  field :current_status_date, type: Date
  field :current_status_description, type: String
  field :display_number, type: String
  field :docs_house_gov_postdate, type: Date
  field :introduced_date, type: Date
  field :is_alive, type: Boolean
  field :is_current, type: Boolean
  field :link, type: String
  field :number, type: Integer
  field :resource_uri, type: String
  field :senate_floor_schedule_postdate, type: Date
  field :thomas_link, type: String

  # my additions
  #field :bill_html, :type => String
  field :ident, :type => String
  field :cosponsors_count, :type => Integer
  field :govtrack_name, type: String
  field :summary_word_count, :type => Integer
  field :text_word_count, :type => Integer
  field :text_updated_on, :type => Date
  field :hidden, :type => Boolean
  field :roll_time, :type => DateTime

  index({title: 1}, {unique: true})
  index({bill_type: 1}, {unique: true})
  index({created_at: 1}, {unique: true})
  index({govtrack_name: 1}, {unique: true})
  index({roll_time: 1}, {unique: true})

  # #####################
  # SCOPES
  scope :house_bills, where(title: /^h/).desc(:vote_count)
  scope :senate_bills, where(title: /^s/).desc(:vote_count)
  scope :introduced_house_bills, where(title: /^h/).and(bill_state: /^INTRODUCED|REPORTED|REFERRED$/).desc(:introduced_date)
  scope :introduced_senate_bills, where(title: /^s/).and(bill_state: /^INTRODUCED|REPORTED|REFERRED$/).desc(:introduced_date)
  scope :rolled_bills, where(:roll_time.ne => nil).descending(:roll_time)

  # #####################
  # ASSOCIATIONS

  has_many :comments, as: :commentable

  belongs_to :sponsor, :class_name => "Legislator"

  has_and_belongs_to_many :cosponsors, :class_name => "Legislator"
  has_and_belongs_to_many :subjects

  has_many :rolls

  # #####################
  # METHODS

  def type_key
    BILL_TYPE_HASH[self.bill_type.to_sym][:key]
  end

  def current_status_explanation
    "#{BILL_STATUS[self.current_status.to_sym]} on #{self.current_status_date}".html_safe
  end

  def passed?
    !(self.current_status =~ /^pass/).nil?
  end

  def get_bill_text
    response = HTTParty.get(self.bill_html_link).response
    case response
      when 200
        response.body
      else
        nil
    end
  end

  def bill_text?
    response = HTTParty.get(self.bill_html_link).response
    case response.code
      when "200"
        true
      else
        nil
    end
  end

  def bill_html_link
    "#{bill_link}.html"
  end

  def bill_pdf_link
    "#{bill_link}.pdf"
  end

  def bill_link
    "#{GOVTRACK_URL}/data/us/bills.text/#{self.congress.to_s}/#{self.type_key}/#{self.type_key + self.number.to_s}"
  end

  class << self

    def pull_in_bills(congress = 112, limit = 100)
      GovTrack::Bill.find(congress: congress, order_by: "-current_status_date", limit: limit).each do |bill|
        puts "Pulling in #{bill.title}"
        from_govtrack(bill).save!
      end
    end

    def from_govtrack(bill, add_rolls = false, limit = 500)
      b = Bill.new
      b.govtrack_id = bill.id
      b.bill_resolution_type = bill.bill_resolution_type
      b.bill_type = bill.bill_type
      b.congress = bill.congress.to_i
      b.current_status = bill.current_status
      b.current_status_date = bill.current_status_date
      b.current_status_description = bill.current_status_description
      b.display_number = bill.display_number
      b.docs_house_gov_postdate = Date.parse(bill.docs_house_gov_postdate.to_s) if bill.docs_house_gov_postdate
      b.introduced_date = Date.parse(bill.introduced_date.to_s)
      b.is_alive = bill.is_alive
      b.is_current = bill.is_current
      b.link = bill.link
      b.number = bill.number
      b.resource_uri = bill.resource_uri
      b.senate_floor_schedule_postdate = bill.senate_floor_schedule_postdate
      b.thomas_link = bill.thomas_link
      b.title = bill.title
      b.title_without_number = bill.title_without_number
      # lookup
      # add legislator if they don't exist?
      b.save
      if legislator = Legislator.where(govtrack_id: bill.sponsor.id).first
        b.sponsor = legislator
      else
        if legislator = Legislator.find_and_build(bill.sponsor.id)
          legislator.save!
          b.sponsor = legislator
        else
          raise "sponsor not found"
        end
      end
      # add rolls ?
      b.save
      if add_rolls
        #GovTrack::Vote.find(related_bill__congress: b.congress, related_bill__bill_type: b.bill_type, related_bill__number: b.number, order_by: "-created").each do |vote|
        GovTrack::Vote.find(related_bill: bill.id, order_by: "-created").each do |vote|
          roll = Roll.from_govtrack(vote)
          roll.add_votes(limit)
          roll.save!
          b.rolls << roll
        end
      end # add rolls
      b
    end # from govtrack

  end # class self

end

app/controllers/bills_controller.rb
class BillsController < InheritedResources::Base
  load_and_authorize_resource
  has_scope :page, :default => 1

  def show
    @bill = Bill.find(params[:id])
    #@bill_text = @bill.get_bill_text
    # comment fields
    @comment = Comment.new
    @author = current_user.nil? ? "" : current_user.name
    @email = current_user.nil? ? "" : current_user.email
    # # #
    show!
  end

end

app/helpers/bills_helper.rb
module BillsHelper

  def pie_chart(tally)
    # also like Sand and Shade: 8E9E63|E6DBB0|F5EED7|C4BCA0|176573 #
    # used satisfying results by ben.eelen
    # we can also use: DB9E36
    unless tally.values.all? { |t| t==0 }
      chart_root = "http://chart.apis.google.com/chart"
      vals = {
          # what is the size of the chart?
          chs: '70x63',
          # what chart type?
          cht: 'p',
          # what are the chart colors (in the same order as the data)
          # chco=<slice_1>|<slice_2>|<slice_n>,<series_color_1>,...,<series_color_n>
          chco: '1B8598|EE6514|DEE8E8|A5B0B0',
          # Text Format with Custom Scaling
          chds: 'a',
          # the actual data
          chd: "t:#{tally[:ayes]},#{tally[:nays]},#{tally[:abstains]},#{tally[:presents]}",
          # Pie Chart Rotation | chp=<radians>
          chp: '0.0',
          #chma=<left_margin>,<right_margin>,<top_margin>,<bottom_margin>|<opt_legend_width>,<opt_legend_height>
          chma: '|2'
      }
      query = vals.map { |k, v| "#{k}=#{v}" }.join("&")
      alt_tag = tally.map { |k, v| "#{k}: #{v}" }.join(",")
      image_tag("#{chart_root}?#{query}", size: "70x63", alt: alt_tag, style: "box-shadow:none;").html_safe
      #%q{<img src="http://chart.apis.google.com/chart?chs=70x63&cht=p&chco=009900|E20000|76A4FB|990066&chds=-3.333,100&chd=t:32.787,50.82,100,42.623&chp=0.067&chma=|2" width="70" height="63" alt="" />}.html_safe
    else
      "no votes"
    end
  end
end

app/views/bills/_form.html.haml
= simple_form_for(@bill) do |f|
  = f.error_notification

  .form-inputs
    = f.input :bill_resolution_type
    = f.input :bill_type
    = f.input :congress
    = f.input :current_status
    = f.input :current_status_date
    = f.input :current_status_description
    = f.input :display_number
    = f.input :docs_house_gov_postdate
    = f.input :govtrack_id
    = f.input :introduced_date
    = f.input :is_alive
    = f.input :is_current
    = f.input :link
    = f.input :number
    = f.input :resource_uri
    = f.input :senate_floor_schedule_postdate
    = f.input :thomas_link
    = f.input :title
    = f.input :title_without_number

  .form-actions
    = f.button :submit

app/views/bills/_rolls.html.haml
%table.table.zebra-striped
  %tr
    %th File Name
    %th Action
    %th For
    %th Against
    %th Abstain
    %th Present
    %th Result
  - rolls.each do |roll|
    %tr
      %td= link_to roll.file_name, roll
      %td= roll.the_question
      %td= roll.aye
      %td= roll.nay
      %td= roll.nv
      %td= roll.present
      %td= roll.result

app/views/bills/_vote_region.html.haml
= simple_form_for(@vote, url: add_vote_path) do |f|
  = f.error_notification

  .form-inputs
    = f.input :chamber, as: :hidden, input_html: { value: bill.chamber }
    = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
    = f.input :bill_id, as: :hidden, input_html: { value: bill.id }
    = f.input :value, :collection => VOTE_VALUES.map{|v| [v,v]}, :label_method => :last,    |
      :value_method => :first, :as => :radio_buttons, :item_wrapper_class => 'inline' |

  .form-actions
    = f.button :submit

app/views/bills/edit.html.haml
%h1 Editing bill

= render 'form'

= link_to 'Show', @bill
\|
= link_to 'Back', bills_path

app/views/bills/index.html.haml
-title 'Listing bills'

= paginate @bills

%table.table.table-striped
  %tr
    %th{style: 'width: 80%'} Title
    %th Current status
    - if current_user.admin?
      %th
      %th
      %th

  - @bills.each do |bill|
    %tr
      %td= link_to bill.title_without_number, bill_path(bill)
      %td= CURRENT_STATUS[bill.current_status].gsub(/<em>.*<\/em>/,'')
      - if current_user.admin?
        %td= link_to 'Show', bill
        %td= link_to 'Edit', edit_bill_path(bill)
        %td= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' }

= paginate @bills

%br

- if current_user.admin?
  = link_to 'New Bill', new_bill_path

app/views/bills/new.html.haml
%h1 New bill

= render 'form'

= link_to 'Back', bills_path

app/views/bills/show.html.haml
%p#notice= notice

- title @bill.title

%p
  %strong Sponsor:
  = link_to @bill.sponsor.name, legislator_path(@bill.sponsor)

%p
  %strong Introduced:
  = @bill.introduced_date.to_s

%p
  %strong Current status:
  = @bill.current_status_explanation

- if @bill.bill_text?
  %p
    Full bill text
    (
    = link_to 'html', @bill.bill_html_link, target: "_blank"
    |
    = link_to 'pdf', @bill.bill_pdf_link, target: "_blank"
    ) or
    = link_to "View on THOMAS", @bill.thomas_link

- else
  %p Bill text is not yet available

- unless @bill.rolls.empty?
  %h5 Rolls
  %ul
    - @bill.rolls.each do |roll|
      %li= link_to roll.title, roll_path(roll)

= render partial: 'comments/comments_section', locals: {parent: @bill, comment: @comment, author: @author, author_email: @email}

- if current_user.admin?
  = link_to 'Edit', edit_bill_path(@bill)
  \|
  = link_to 'Back', bills_path