config/routes.rb
Polco3::Application.routes.draw do

  resources :roles

  get "home/polco_info"

  resources :rolls do
    resources :comments
  end

  resources :bills do
    resources :comments
  end

  resources :legislators do
    resources :comments
  end

  resources :subjects

  # sign up a user for a district
  match "/users/geocode" => "users#geocode"
  match "/users/save_geocode" => "users#save_geocode"
  match "/users/district" => "users#district"

  get "polco_groups/add_custom_group"
  post "polco_groups/follow_group"
  post "polco_groups/join_group"

  resources :polco_groups do
    resources :comments
  end

  resources :legislator_votes # necessary?
  resources :votes

  resources :identities

  # what bills are active?
  get "represent/house_bills"
  get "represent/senate_bills"
  # how are the legislators voting?
  get "represent/legislators_districts"
  get "represent/states"
  # how are you being represented?
  # H3. and S3 house results -- how represented are you in the house?
  match "/represent/:chamber" => "represent#results", as: :results
  # helper to add vote
  post "rolls/add_vote", as: :add_vote

  root to: "represent#house_bills"
  resources :users, :only => [:index, :show, :edit, :update ] do
    resources :comments
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/signin', to: 'sessions#new', as: :signin
  match '/signout', to: 'sessions#destroy', as: :signout
  match '/auth/failure', to: 'sessions#failure'
end

app/models/subject.rb
class Subject
  # currently not used
  include Mongoid::Document
  field :name, :type => String
  index({ name: 1}, {unique: true})

  has_and_belongs_to_many :bills
  #validates_uniqueness_of :name

end

app/controllers/subjects_controller.rb
class SubjectsController < InheritedResources::Base
  has_scope :page, :default => 1
  load_and_authorize_resource
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= simple_form_for @subject, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    = f.input :name
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to 'cancel', subjects_path, :class => 'btn'

app/views/subjects/edit.html.haml
- model_class = Subject
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/subjects/index.html.haml
- model_class = Subject

- title 'Subjects'

= paginate @subjects

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th Actions
  %tbody
    - @subjects.each do |subject|
      %tr
        %td= link_to subject.name, subject_path(subject)
        %td
          = link_to 'Edit', edit_subject_path(subject), :class => 'btn btn-mini'
          = link_to 'Destroy', subject_path(subject), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger'

= link_to 'New', new_subject_path, :class => 'btn btn-primary'

= paginate @subjects

app/views/subjects/new.html.haml
- model_class = Subject
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/subjects/show.html.haml
- model_class = Subject
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:_type) + ':'
  %br
  = @subject._type
%p
  %strong= model_class.human_attribute_name(:_id) + ':'
  %br
  = @subject._id
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @subject.name

.form-actions
  = link_to 'back', subjects_path, :class => 'btn'
  = link_to 'Edit', edit_subject_path(@subject), :class => 'btn'
  = link_to 'Destroy', subject_path(@subject), :method => "delete", :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'