config/routes.rb
Polco3::Application.routes.draw do

  resources :roles

  get "home/polco_info"

  resources :rolls do
    resources :comments
  end

  resources :bills do
    resources :comments
  end

  resources :legislators do
    resources :comments
  end

  resources :subjects

  # sign up a user for a district
  match "/users/geocode" => "users#geocode"
  match "/users/save_geocode" => "users#save_geocode"
  match "/users/district" => "users#district"

  get "polco_groups/add_custom_group"
  post "polco_groups/follow_group"
  post "polco_groups/join_group"

  resources :polco_groups do
    resources :comments
  end

  resources :legislator_votes # necessary?
  resources :votes

  resources :identities

  # what bills are active?
  get "represent/house_bills"
  get "represent/senate_bills"
  # how are the legislators voting?
  get "represent/legislators_districts"
  get "represent/states"
  # how are you being represented?
  # H3. and S3 house results -- how represented are you in the house?
  match "/represent/:chamber" => "represent#results", as: :results
  # helper to add vote
  post "rolls/add_vote", as: :add_vote

  root to: "represent#house_bills"
  resources :users, :only => [:index, :show, :edit, :update ] do
    resources :comments
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/signin', to: 'sessions#new', as: :signin
  match '/signout', to: 'sessions#destroy', as: :signout
  match '/auth/failure', to: 'sessions#failure'
end

app/models/polco_group.rb
class PolcoGroup
  include Mongoid::Document
  include Mongoid::Timestamps
  include VotingMethods
  #include Origin::Queryable

  # verify this list!
  #attr_accessible :name, :type, :description, :vote_count, :follower_count, :member_count, :owner_id, :member_ids, :common_member_ids, :follower_ids, :vote_ids, :rep_id

  field :name, :type => String
  field :type, :type => Symbol, :default => :custom
  field :description, :type => String
  field :vote_count, :type => Integer, :default => 0
  field :follower_count, :type => Integer, :default => 0
  field :member_count, :type => Integer, :default => 0

  index({ name: 1}, {unique: true})
  index({ type: 1}, {unique: true})
  index({ follower_count: 1}, {unique: true})
  index({ member_count: 1}, {unique: true})
  index({ vote_count: 1}, {unique: true})

  # this might be trouble, a user might not "own" this if they are just in the custom groups (by the way i understood it)
  belongs_to :owner, :class_name => "User", :inverse_of => :custom_groups

  has_many :district_citizens, class_name: "User", inverse_of: :district
  has_many :state_citizens, class_name: "User", inverse_of: :state

  belongs_to :rep, class_name: "Legislator", inverse_of: :legislator_district
  has_many :state_legislators, class_name: "Legislator", :inverse_of => :legislator_state

  has_and_belongs_to_many :members, :class_name => "User", :inverse_of => :joined_groups # uniq: true
  has_and_belongs_to_many :common_members, :class_name => "User", :inverse_of => :common_groups # uniq: true
  has_and_belongs_to_many :followers, :class_name => "User", :inverse_of => :followed_groups #, uniq: true

  has_many :votes, as: :votable

  has_many :comments, as: :commentable

  def get_tally(roll)
    process_votes(self.votes.where(roll_id: roll.id))
  end

  def self.column_names
    self.fields.collect { |field| field[0] }
  end

  def add_member(user_obj)
    self.members.push(user_obj)
    self.member_count += 1
    self.save
  end

  def add_follower(user_obj)
    self.followers.push(user_obj)
    self.follower_count += 1
    self.save
  end

  # some validations
  validates_uniqueness_of :name, :scope => :type
  validates_inclusion_of :type, :in => [:custom, :state, :district, :common, :country], :message => 'Only valid groups are custom, state, district, common, country'

  scope :states, where(type: :state)
  scope :districts, where(type: :district).desc(:member_count)
  scope :districts_with_activity, where(type: :district).and(:vote_count.gt => 0).desc(:member_count)
  scope :customs, where(type: :custom)
  scope :most_followed, desc(:follower_count)
  scope :most_members, desc(:member_count)
  scope :most_votes, desc(:vote_count)
  scope :find_district, ->(district_name) { where(type: :district).and(name: district_name) }

  # time to create the ability to follow
  #before_update :update_counters

  def update_counters # not currently called . . . !
    self.follower_count = self.follower_ids.size
    self.member_count = self.member_ids.size
    self.vote_count = self.votes.size
  end

  def has_activity?(roll)
    # does the group have any polco activity?
    self.votes.where(roll_id: roll.id).size > 0
  end

  def senators_hash
    # polcoGroup must be a state
    if (self.type == :state) && (Legislator.senators.where(state: self.name).size == 2)
      legs = Legislator.senators.where(state: self.name).sort_by { |u| u.current_role.startdate }
      {junior_senator: legs.last, senior_senator: legs.first}
    else
      nil
    end
  end

  def self.states_with_senators
    collection = []
    PolcoGroup.states.each do |state|
      if h = state.senators_hash
        collection << {state: state, junior_senator: h[:junior_senator], senior_senator: h[:senior_senator]}
      end
    end
    collection
  end

  #def has_senator?
  #  (self.type == :state) && (!self.senators_hash.all? {|k,v| v.nil?})
  #end

  def find_the_rep
    # just in case we need to match a district to a legislator
    # this method finds the rep of a district
    # not used for current code base
    if self.type == :district && self.name
      if self.name =~ /([A-Z]{2})-AL/ # then there is only one district
        puts "The district is named #{self.name}"
        l = Legislator.where(state: $1).where(district: 0).first
      else # we have multiple districts for this state
        data = self.name.match(/([A-Z]+)(\d+)/)
        state, district_num = data[1], data[2].to_i
        l = Legislator.representatives.where(state: state).and(district: district_num).first
        self.rep = l
        self.save!
        #l = Legislator.all.select { |l| l.district_name == self.name }.first
      end
    else
      l = "Only districts can have a representative"
    end
    l || "Vacant"
  end

  def get_votes_tally(roll)
    process_votes(self.votes.where(roll_id: roll.id).all.to_a)
  end

  def format_votes_tally(roll)
    v = process_votes(self.votes.where(roll_id: roll.id).all.to_a)
    "#{v[:ayes]}, #{v[:nays]}, #{v[:abstains]}"
  end

  def senators
    if self.type == :state
      Legislator.senators.where(state: self.name).all.to_a
    else
      nil
    end
  end

  def senators_parties
    self.senators.map{|s| s.current_role.party[0]}.join(", ")
  end

  def proper_title
    if (self.type == :custom) && !self.name.nil?
      self.name.titlecase
    else
      self.name
    end
  end

end

app/controllers/polco_groups_controller.rb
class PolcoGroupsController < InheritedResources::Base
  has_scope :page, default: 1
  helper_method :sort_column, :sort_direction
  #respond_to :js, only: [:join_group, :follow_group]
  load_and_authorize_resource

  def add_custom_group
    @polco_group = PolcoGroup.new
  end

  def index
    if params[:direction].to_s == "asc"
      @polco_groups = PolcoGroup.asc(params[:sort].downcase.to_sym).all.page(params[:page]).per(10)
    elsif params[:direction].to_s == "desc"
      @polco_groups = PolcoGroup.desc(params[:sort].downcase.to_sym).all.page(params[:page]).per(10)
    else
      @polco_groups = PolcoGroup.all.page(params[:page]).per(20)
    end
  end

  def join_group
    pg = PolcoGroup.find(params[:join_group][:polco_group_id])
    user = User.find(params[:join_group][:user_id])
    pg.add_member(user)
    @members = pg.members
  end

  def follow_group
    pg = PolcoGroup.find(params[:follow_group][:polco_group_id])
    user = User.find(params[:follow_group][:user_id])
    pg.add_follower(user)
    @followers = pg.followers
  end

  def create
    @polco_group = PolcoGroup.new(params[:polco_group])
    @polco_group.owner = current_user
    if @polco_group.save
      if params[:polco_group][:type] == 'custom' && params[:add_custom_group]
        # then a user is creating a new custom group
        @polco_group.add_member(current_user)
      end
      redirect_to @polco_group, notice: "Custom Group \"#{@polco_group.name}\" was successfully completed"
    else
      render :new
    end
  end

  def show
    @polco_group = PolcoGroup.find(params[:id])
    @comment = Comment.new
    @user = current_user
    @author = @user.nil? ? "" : @user.name
    @email = @user.nil? ? "" : @user.email
    @rolls =  @polco_group.votes.map{|v| v.roll}.uniq
    show!
  end

  private

  def sort_column
    PolcoGroup.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/polco_groups_helper.rb
module PolcoGroupsHelper
end

app/views/polco_groups/_district_info.html.haml
%p
  special district information: maps, reps
  = group.name

app/views/polco_groups/_form.html.haml
= simple_form_for @polco_group, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :type, collection: GROUP_TYPES
  = f.input :description
  = f.input :vote_count
  = f.input :follower_count
  = f.input :member_count
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to 'cancel', polco_groups_path, :class => 'btn'

app/views/polco_groups/_join_form.html.haml
= simple_form_for :join_group, url: '/polco_groups/join_group', :html => { class: 'form-horizontal', id: 'join_group_form'}, remote: true do |f|
  = f.input :user_id, as: :hidden, input_html: {value: u.id}
  = f.input :polco_group_id, as: :hidden, input_html: {value: g.id}
  = f.button :submit, 'Join Group', class: 'btn btn-danger'

app/views/polco_groups/_show_member.html.haml
- if members.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th Name
    - members.each do |member|
      %tr
        %td
          = link_to member.name, member

app/views/polco_groups/_state_info.html.haml
%p
  special state information: maps, senators
%p
  %strong State Name:
  = state.name

app/views/polco_groups/add_custom_group.html.haml
- title "Add Custom Group"

= simple_form_for @polco_group, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    = f.input :name
    = f.input :type, value: :custom, as: :hidden
    = text_field_tag :add_custom_group, 'yes', {type: 'hidden'}
    = f.input :description, as: :text
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to 'cancel', polco_groups_path, :class => 'btn'

app/views/polco_groups/edit.html.haml
- model_class = PolcoGroup
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/polco_groups/follow_group.js.erb
$("#follow_group_region").html("<p>You are following this group.</p>")
$("#follower_count").html(parseInt($("#follower_count").html()) + 1);
var html = "<%= escape_javascript(render(partial: "show_member", locals: {members: @followers})) %>";
$("#the_followers").html(html);

app/views/polco_groups/index.html.haml
- title 'Polco Groups'

= paginate @polco_groups

%table.table.table-striped
  %thead
    %tr
      %th= sortable "name", "Name"
      %th= sortable "type", "Type"
      %th= sortable "description", "Description"
      %th= sortable "vote_count", "Votes"
      %th= sortable "follower_count", "Followers"
      %th= sortable "member_count", "Members"
      - if current_user.admin?
        %th Actions
  %tbody
    - @polco_groups.each do |polco_group|
      %tr
        %td= link_to polco_group.name, polco_group_path(polco_group)
        %td= polco_group.type
        %td= polco_group.description
        %td= polco_group.vote_count
        %td= polco_group.follower_count
        %td= polco_group.member_count
        - if current_user.admin?
          %td
            = link_to 'edit', edit_polco_group_path(polco_group), :class => 'btn btn-mini'
            = link_to 'destroy', polco_group_path(polco_group), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger'

- if current_user.admin? #can? :create, PolcoGroup
  = link_to 'New', new_polco_group_path, :class => 'btn btn-primary'

= paginate @polco_groups

app/views/polco_groups/join_group.js.erb
$("#join_group_region").html("<p>You have joined this group.</p>")
$("#member_count").html(parseInt($("#member_count").html()) + 1);
var html = "<%= escape_javascript(render(partial: "show_member", locals: {members: @members})) %>";
$("#the_members").html(html);

app/views/polco_groups/new.html.haml
- model_class = PolcoGroup
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/polco_groups/show.html.haml
- title "#{@polco_group.type.to_s.titlecase} Group: #{@polco_group.proper_title}"

- unless @polco_group.description.nil? || @polco_group.description.empty?
  %h4 Group Description
  %p= @polco_group.description

%h4
  Group Formation Date:
  = @polco_group.created_at.strftime('%B %e, %Y')

- if (@polco_group.type == :custom) && @polco_group.owner
  %h4
    Owned by:
    = link_to @polco_group.owner.name, @polco_group.owner

- case @polco_group.type
  - when :district
    = render partial: "district_info", locals: {group: @polco_group}
  - when :state
    = render partial: "state_info", locals: {state: @polco_group}

%p
  %strong Votes:
  = @polco_group.vote_count

- if @rolls.size > 0
  %h3 Group Tally
  .well
    %table.table.table-striped
      %tr
        %th Roll
        %th For
        %th Against
        %th Other
        %th Result
      - @rolls.each do |roll|
        %tr
          %td= link_to roll.title, roll_path(roll)
          - roll_result = @polco_group.get_tally(roll) # is this the district tally
          %td= roll_result[:ayes]
          %td= roll_result[:nays]
          %td= roll_result[:other]
          %td= roll.bill.passed? ? "Yes" : "No" # should be the full result

= render partial: 'comments/comments_section', locals: {parent: @polco_group, comment: @comment, author: @author, author_email: @email}

%h4
  %span#member_count
    = @polco_group.member_count
  members

#the_members
  = render partial: "show_member", locals: {members: @polco_group.members}

- unless @user.has_joined(@polco_group)
  #join_group_region
    = render partial: "join_form", locals: {g: @polco_group, u: @user}
- else
  %p You have joined this group

%h4
  %span#follower_count
    = @polco_group.follower_count
  followers

#the_followers
  = render partial: "show_member", locals: {members: @polco_group.followers}

- unless @user.has_followed(@polco_group)
  #follow_group_region
    = simple_form_for :follow_group, url: '/polco_groups/follow_group', :html => { class: 'form-horizontal', id: 'follow_group_form' }, remote: true do |f|
      = f.input :user_id, as: :hidden, input_html: {value: @user.id}
      = f.input :polco_group_id, as: :hidden, input_html: {value: @polco_group.id}
      = f.button :submit, 'Follow Group', class: 'btn btn-danger'
- else
  %p You are following this group

- if @user.admin? || @user.id == @polco_group.owner_id
  .form-actions
    = link_to 'back', polco_groups_path, :class => 'btn'
    = link_to 'edit', edit_polco_group_path(@polco_group), :class => 'btn'
    = link_to 'destroy', polco_group_path(@polco_group), :method => "delete", :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'